app:
  base-url: http://localhost:8080

api:
  apiKeys:
    - keyvalue: foobar
      refreshAddress: http://localhost:8081/success
      dataGroups: [DG4,DG5,DG17]
    - keyvalue: foobar2
      refreshAddress: https://foobar2.com
      dataGroups: [DG1,DG2, DG3]

eidservice:
  wsdl-url: https://test.governikus-eid.de/eID-Server-230/eID?wsdl
  url: https://test.governikus-eid.de:8444/eID-Server-230/eID
  tls-cert: classpath:eid-server-certificates/local/test.governikus-eid.de.cer
  sig-cert: classpath:eid-server-certificates/local/test-wssign.governikus-eid.de.cer
  truststore-password: 123456
  soap-tls-keystore:
    keystore: classpath:soap-certificates/local/Digital_Service_Webservice_Authentication_123456.p12
    type: PKCS12
    alias: "webservice authentication"
    password: 123456
  soap-sig-keystore:
    keystore: classpath:soap-certificates/local/Digital_Service_Webservice_Signature_123456.p12
    type: PKCS12
    alias: "webservice signature"
    password: 123456

spring:
  #  r2dbc:
  #    url: r2dbc:postgresql://localhost:5432/useid
  #    username: root
  #    password: secret
  #    properties:
  #      sslMode: disable
  flyway:
    url: jdbc:postgresql://localhost:5432/useid
    user: root
    password: secret
  datasource:
    url: jdbc:postgresql://localhost:5432/useid
    username: root
    password: secret

csp:
  allowed-hosts:
    - foo.bar
    - bar.foo
    - localhost:8081

features:
  desktop-solution-enabled: true
