app:
  base-url: http://localhost:8080

tenant:
  tenants:
    - id: tenantFoo
      apiKey: foobar
      refreshAddress: http://localhost:8081/success
      dataGroups:
        - DG4
        - DG5
        - DG17
      allowedHosts:
        - "localhost:8081"
        - "foo.2.local"

eidservice:
  wsdl-url: https://test.governikus-eid.de/eID-Server-230/eID?wsdl
  url: https://test.governikus-eid.de:8444/eID-Server-230/eID
  tls-cert: classpath:eid-server-certificates/local/test.governikus-eid.de.cer
  sig-cert: classpath:eid-server-certificates/local/test-wssign.governikus-eid.de.cer
  truststore-password: 123456
  soap-tls-keystore:
    keystore: classpath:soap-certificates/local/Digital_Service_Webservice_Authentication_123456.p12
    type: PKCS12
    alias: "webservice authentication"
    password: 123456
  soap-sig-keystore:
    keystore: classpath:soap-certificates/local/Digital_Service_Webservice_Signature_123456.p12
    type: PKCS12
    alias: "webservice signature"
    password: 123456

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/useid
    username: root
    password: secret

tracking:
  matomo:
    siteId: "5"
    dimensionIdTenant: "3"

features:
  desktop-solution-enabled: true

springdoc:
  show-actuator: true
