management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
      discovery:
        enabled: false
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
  info:
    kubernetes:
      enabled: false

server:
  shutdown: graceful
  error:
    include-message: never
    include-stacktrace: never
  tomcat:
    basedir: /tmp/tomcat

spring:
  jackson:
    serialization:
      indent_output: true
#  r2dbc:
#    pool:
#      enabled: true
#      initial-size: 10
#      max-size: 20
#    properties:
#      sslMode: require


springdoc:
  api-docs:
    path: /v1
  swagger-ui:
    path: /swagger/docs.html
    operationsSorter: method

eidservice:
  truststore-password: # set via environment
  soap-tls-keystore:
    keystore: file:/etc/secrets/soap-keystore/soap-keystore.jks
    type: JKS
    alias: soap-enc
    password: # set via environment
  soap-sig-keystore:
    keystore: file:/etc/secrets/soap-keystore/soap-keystore.jks
    type: JKS
    alias: soap-sig
    password: # set via environment

wellknown:
  ios-config:
    app-id: "VDTVKQ35RL.de.bund.digitalservice.UseID"
    app-id-preview: "VDTVKQ35RL.de.bund.digitalservice.UseID-Preview"
    path-url: "/eID-Client"

  android-config:
    relation: "delegate_permission/common.handle_all_urls"
    namespace: "android_app"
    package-default:
      name: "de.digitalService.useID"
      fingerprint: "38:3A:63:60:60:BE:0B:E9:40:AB:F8:67:EA:BB:64:C8:91:99:0B:DC:01:D8:3D:34:89:A6:29:E4:1D:3B:85:9F"
    package-preview:
      name: "de.digitalService.useID.Preview"
      fingerprint: "15:7E:42:A7:92:6B:A5:CA:9E:B0:29:8E:88:EE:81:0D:C3:13:E9:B5:84:41:50:28:8A:88:17:B4:14:40:FB:42"

csp:
  default-config: "default-src 'self';script-src 'self';style-src 'self';font-src 'self';img-src 'self';connect-src 'self';"
  frame-ancestors: "frame-ancestors 'self'"

features:
  desktop-solution-enabled: false
