management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

server:
  shutdown: graceful

springdoc:
  api-docs:
    path: /v1
  swagger-ui:
    path: /swagger/docs.html
    operationsSorter: method

#spring:
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres