management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
      discovery:
        enabled: false
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
  info:
    kubernetes:
      enabled: false

server:
  shutdown: graceful
  error:
    include-message: never
    include-stacktrace: never

spring:
  jackson:
    serialization:
      indent_output: true
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
    properties:
      sslMode: require

springdoc:
  api-docs:
    path: /v1
  swagger-ui:
    path: /swagger/docs.html
    operationsSorter: method

eidservice:
  truststore-password: # set via environment
  soap-tls-keystore:
    keystore: file:/etc/secrets/soap-keystore/soap-keystore.jks
    type: JKS
    alias: soap-enc
    password: # set via environment
  soap-sig-keystore:
    keystore: file:/etc/secrets/soap-keystore/soap-keystore.jks
    type: JKS
    alias: soap-sig
    password: # set via environment

wellknown:
  ios-config:
    app-id: "VDTVKQ35RL.de.bund.digitalservice.UseID"
    app-id-preview: "VDTVKQ35RL.de.bund.digitalservice.UseID-Preview"
    path-url: "/eID-Client"

  android-config:
    relation: "delegate_permission/common.handle_all_urls"
    namespace: "android_app"
    package-default:
      name: "de.digitalService.useID"
      fingerprint: "38:3A:63:60:60:BE:0B:E9:40:AB:F8:67:EA:BB:64:C8:91:99:0B:DC:01:D8:3D:34:89:A6:29:E4:1D:3B:85:9F"
    package-preview:
      name: "de.digitalService.useID.Preview"
      fingerprint: "15:7E:42:A7:92:6B:A5:CA:9E:B0:29:8E:88:EE:81:0D:C3:13:E9:B5:84:41:50:28:8A:88:17:B4:14:40:FB:42"

csp:
  default-config: "default-src 'self';script-src 'self';style-src 'self';font-src 'self';img-src 'self';connect-src 'self';"
  frame-ancestors: "frame-ancestors 'self'"

widget:
  meta-tag:
    header-title: DigitalService GmbH des Bundes
  main-view:
    localization:
      headline-title-top: Mit BundesIdent
      headline-title-bottom: online ausweisen
      headline-image-alt: "Drei Ausweisdokumente: Personalausweis, elektronischer Aufenthaltstitel und die eID-Karte für Bürgerinnen und Bürger:innen:innen der Europäischen Union und des Europäischen Wirtschaftsraums"
      app-icon-image-alt: "App Icon: Weißer Bundesadler auf blauem Grund"
      step-one-alt: Schritt eins
      step-two-alt: Schritt zwei
      download-title: BundesIdent installieren
      app-store-alt: Aus dem Apple App Store laden
      play-store-alt: Aus dem Google Play Store laden
      identification-button: Mit BundesIdent ausweisen
      identification-button-aria-label: Öffnet die BundesIdent App zum ausweisen
      data-privacy-button: Datenschutzerklärung
      open-in-new-tab: Öffnet in einem neuen Fenster

    mobile-url:
      app-store-url: https://apps.apple.com/de/app/bundesident/id1635758944
      play-store-url: https://play.google.com/store/apps/details?id=de.digitalService.useID
      data-privacy: https://digitalservice.bund.de/datenschutzerklaerung-bundesident

  error-view:
    incompatible:
      localization:
        headline-title: Ihr Smartphone erfüllt leider nicht die Voraussetzungen der BundesIdent App.
        requirement-title: "Mindestvoraussetzungen:"
        android-title: Android
        android-requirement: Android 9 »Pie« und ein NFC-Sensor.
        iphone-title: iPhone
        iphone-requirement: iOS 15 & iPhone 7.
    fallback:
      localization:
        error-title: Es ist ein Fehler aufgetreten.
        error-text: Stellen Sie sicher, dass die BundesIdent App installiert ist und versuchen Sie es erneut.
