app:
  base-url: https://useid.dev.ds4g.net

eidservice:
  url: https://eid-epan1-ref.eid-service.de:9443/eID-Server-240
  tls-cert: classpath:eid-server-certificates/panstar/dev.id.governikus-eid.de.cer
  sig-cert: classpath:eid-server-certificates/panstar/dev.id.governikus-eid.de-ws-sig.cer

sentry:
  environment: staging
  traces-sample-rate: 0.1

features:
  desktop-solution-enabled: true

springdoc:
  show-actuator: true
