app:
  base-url: http://localhost:8080

feature:
  eid-service-integration:
    enabled: true

api:
  apiKeys:
    - keyvalue: foobar
      refreshAddress: https://foobar.com
      dataGroups: [DG1,DG2]
