app:
  base-url: https://useid.dev.ds4g.net

eidservice:
  wsdl-url: https://eid-ref1.eid-service.de/eID-Server-230/eID?wsdl
  url: https://eid-ref1.eid-service.de:9443/eID-Server-230/eID
  tls-cert: classpath:eid-server-certificates/dev/dev-dtrust-eid-tls.cer
  sig-cert: classpath:eid-server-certificates/dev/dev-dtrust-eid-sig.cer

sentry:
  environment: staging
  traces-sample-rate: 0.1

tracking:
  matomo:
    siteId: "2"
    dimensionIdTenant: "1"

features:
  desktop-solution-enabled: true # PROTOTYPE LINE

springdoc:
  show-actuator: true
