app:
  base-url: http://localhost:8080

api:
  apiKeys:
    - keyValue: foobar
      refreshAddress: http://localhost:8081/success
      dataGroups: [DG4,DG5,DG17]
      tenantId: foobar_tenant_id
    - keyValue: foobar2
      refreshAddress: https://foobar2.com
      dataGroups: [DG1,DG2, DG3]
      tenantId: foobar2_tenant_id

eidservice:
  wsdl-url: https://test.governikus-eid.de/eID-Server-230/eID?wsdl
  url: https://test.governikus-eid.de:8444/eID-Server-230/eID
  tls-cert: classpath:eid-server-certificates/local/test.governikus-eid.de.cer
  sig-cert: classpath:eid-server-certificates/local/test-wssign.governikus-eid.de.cer
  truststore-password: 123456
  soap-tls-keystore:
    keystore: classpath:soap-certificates/local/Digital_Service_Webservice_Authentication_123456.p12
    type: PKCS12
    alias: "webservice authentication"
    password: 123456
  soap-sig-keystore:
    keystore: classpath:soap-certificates/local/Digital_Service_Webservice_Signature_123456.p12
    type: PKCS12
    alias: "webservice signature"
    password: 123456

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/useid
    username: root
    password: secret

csp:
  allowed-hosts:
    - host: foo.bar
      tenantId: foo_bar_tenant_id
    - host: bar.foo
      tenantId: bar_foo_tenant_id
    - host: localhost:8081
      tenantId: localhost_tenant_id

features:
  desktop-solution-enabled: true

springdoc:
  show-actuator: true