app:
  max-percentage-of-eid-failures: ${MAX_PERCENTAGE_OF_EID_FAILURES}

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
      discovery:
        enabled: false
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
  info:
    kubernetes:
      enabled: false

server:
  shutdown: graceful
  error:
    include-message: never
    include-stacktrace: never
  tomcat:
    basedir: /tmp/tomcat

spring:
  jackson:
    serialization:
      indent_output: true
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  data:
    redis:
      repositories:
        enabled: true
      username: default

springdoc:
  api-docs:
    path: /api/docs.json
  swagger-ui:
    path: /api/docs
    operationsSorter: method

eidservice:
  truststore-password: # set via environment
  soap-tls-keystore:
    keystore: file:/etc/secrets/soap-keystore/soap-keystore.jks
    type: JKS
    alias: soap-enc
    password: # set via environment
  soap-sig-keystore:
    keystore: file:/etc/secrets/soap-keystore/soap-keystore.jks
    type: JKS
    alias: soap-sig
    password: # set via environment

wellknown:
  ios-config:
    app-id: "VDTVKQ35RL.de.bund.digitalservice.UseID"
    app-id-preview: "VDTVKQ35RL.de.bund.digitalservice.UseID-Preview"
    app-id-prototype: "VDTVKQ35RL.de.bund.digitalservice.UseID-Prototype"
    path-url: "/eID-Client"

  android-config:
    relation: "delegate_permission/common.handle_all_urls"
    namespace: "android_app"
    package-default:
      name: "de.digitalService.useID"
      fingerprint: "38:3A:63:60:60:BE:0B:E9:40:AB:F8:67:EA:BB:64:C8:91:99:0B:DC:01:D8:3D:34:89:A6:29:E4:1D:3B:85:9F"
    package-preview:
      name: "de.digitalService.useID.Preview"
      fingerprint: "15:7E:42:A7:92:6B:A5:CA:9E:B0:29:8E:88:EE:81:0D:C3:13:E9:B5:84:41:50:28:8A:88:17:B4:14:40:FB:42"

features:
  desktop-solution-enabled: false
