app:
  base-url: http://localhost:8080

api:
  apiKeys:
    - keyvalue: foobar
      refreshAddress: https://foobar.com
      dataGroups: [DG1,DG2]

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/useid
    username: root
    password: secret
  flyway:
    url: jdbc:postgresql://localhost:5432/useid
    user: root
    password: secret