management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

server:
  shutdown: graceful
  error:
    include-message: never
    include-stacktrace: never

springdoc:
  api-docs:
    path: /v1
  swagger-ui:
    path: /swagger/docs.html
    operationsSorter: method
